// Generated from electrical_engineering_question_bank_250000/question_database.csv.
// Do not edit by hand; run `pnpm sync:bank` when the source database changes.

export const generatedBankSummary = {
  "totalQuestions": 250000,
  "expectedQuestions": 250000,
  "topicCount": 20,
  "levels": 25,
  "questionsPerTopic": 12500,
  "questionsPerLevel": 500,
  "templates": 100,
  "svgDiagrams": 12500,
  "latexSources": 12500,
  "imageBackedQuestions": 12500,
  "factCheckedQuestions": 250000,
  "refinedQuestions": 20000,
  "reshuffledAnswerKeys": 250000,
  "contentVersion": "2.0",
  "validationStatus": "PASS",
  "updatedAt": "2026-07-23T16:40:11.109577+00:00"
} as const;

export const generatedBankSignals = [
  {
    "label": "Question rows",
    "value": "250,000",
    "detail": "20 topics x 25 levels"
  },
  {
    "label": "Fact checks",
    "value": "250,000",
    "detail": "Deterministic recomputation with zero failures"
  },
  {
    "label": "SVG diagrams",
    "value": "12,500",
    "detail": "Version 2.0 instructional-hint assets"
  },
  {
    "label": "Content version",
    "value": "v2.0",
    "detail": "250,000 answer keys reshuffled"
  }
] as const;
export const generatedTopicSignals = [
  {
    "id": "dc-circuit-analysis",
    "topic": "DC Circuit Analysis",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "ac-phasors-and-impedance",
    "topic": "AC Phasors and Impedance",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "network-theorems-and-two-port-networks",
    "topic": "Network Theorems and Two-Port Networks",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "transient-circuit-analysis",
    "topic": "Transient Circuit Analysis",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "electromagnetics",
    "topic": "Electromagnetics",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "transmission-lines",
    "topic": "Transmission Lines",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "power-systems",
    "topic": "Power Systems",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "transformers-and-electrical-machines",
    "topic": "Transformers and Electrical Machines",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "power-electronics",
    "topic": "Power Electronics",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "analog-electronics-and-op-amps",
    "topic": "Analog Electronics and Op-Amps",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "semiconductor-devices",
    "topic": "Semiconductor Devices",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "digital-logic",
    "topic": "Digital Logic",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "signals-and-systems",
    "topic": "Signals and Systems",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "control-systems",
    "topic": "Control Systems",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "communications",
    "topic": "Communications",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "measurement-and-instrumentation",
    "topic": "Measurement and Instrumentation",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "pcb-design-and-signal-integrity",
    "topic": "PCB Design and Signal Integrity",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "embedded-systems",
    "topic": "Embedded Systems",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "rf-and-antennas",
    "topic": "RF and Antennas",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  },
  {
    "id": "electrical-safety-and-protection",
    "topic": "Electrical Safety and Protection",
    "questions": 12500,
    "imageCount": 625,
    "minLevel": 1,
    "maxLevel": 25
  }
] as const;

export const generatedLessonQuestions = [
  {
    "id": "EE-00001",
    "topic": "DC Circuit Analysis",
    "subtopic": "Ohm's law",
    "prompt": "An 8 V source is applied across a 8 ohm resistor. What current flows?",
    "diagram": "/question-bank/images/IMG-0001.svg",
    "diagramAlt": "Ohm's law problem diagram for EE-00001",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "18 A",
      "7 A",
      "1 A",
      "2 A",
      "9 A",
      "17 A"
    ],
    "correctIndex": 2,
    "explanation": "Ohm's law gives I = V/R = 8 V/8 ohm = 1 A. Governing relation: I = V/R. Assumptions: Ideal resistor; DC steady state. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-0001",
    "imageRole": "instructional_hint",
    "treePath": "Section 01 > DC Circuit Analysis > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-12501",
    "topic": "AC Phasors and Impedance",
    "subtopic": "Sinusoid to RMS phasor",
    "prompt": "A voltage is v(t) = 18 V cos(omega t + 30 deg). What is the RMS phasor magnitude?",
    "diagram": "/question-bank/images/IMG-0626.svg",
    "diagramAlt": "Sinusoid to RMS phasor problem diagram for EE-12501",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "12.65 V",
      "12.81 V",
      "12.73 V",
      "12.64 V",
      "12.79 V",
      "12.71 V"
    ],
    "correctIndex": 2,
    "explanation": "RMS magnitude equals peak/sqrt(2), so 18/sqrt(2) = 12.73 V. Governing relation: Vrms = Vpeak/sqrt(2). Assumptions: Sinusoidal steady state; magnitude only. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-0626",
    "imageRole": "instructional_hint",
    "treePath": "Section 02 > AC Phasors and Impedance > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-25001",
    "topic": "Network Theorems and Two-Port Networks",
    "subtopic": "Thevenin to Norton",
    "prompt": "A Thevenin equivalent has Vth = 26 V and Rth = 6 ohm. What is the Norton current magnitude?",
    "diagram": "/question-bank/images/IMG-1251.svg",
    "diagramAlt": "Thevenin to Norton problem diagram for EE-25001",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "4.42 A",
      "4.24 A",
      "4.27 A",
      "4.40 A",
      "4.35 A",
      "4.33 A"
    ],
    "correctIndex": 5,
    "explanation": "Norton current is In = Vth/Rth = 4.33 A. Governing relation: IN = Vth/Rth. Assumptions: Linear Thevenin/Norton source equivalence. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-1251",
    "imageRole": "instructional_hint",
    "treePath": "Section 03 > Network Theorems and Two-Port Networks > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-37501",
    "topic": "Transient Circuit Analysis",
    "subtopic": "RC time constant",
    "prompt": "An RC circuit has R = 7 kohm and C = 30 uF. What is the time constant?",
    "diagram": "/question-bank/images/IMG-1876.svg",
    "diagramAlt": "RC time constant problem diagram for EE-37501",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "209 ms",
      "216 ms",
      "218 ms",
      "203 ms",
      "210 ms",
      "212 ms"
    ],
    "correctIndex": 4,
    "explanation": "Time constant tau = RC = 210 ms. Governing relation: tau = RC. Assumptions: First-order ideal RC circuit. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-1876",
    "imageRole": "instructional_hint",
    "treePath": "Section 04 > Transient Circuit Analysis > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-50001",
    "topic": "Electromagnetics",
    "subtopic": "Coulomb force",
    "prompt": "Two point charges, 3 uC and 4 uC, are separated by 0.2 m in air. Using k = 8.98755e9 N m^2/C^2, what is the force magnitude?",
    "diagram": "/question-bank/images/IMG-2501.svg",
    "diagramAlt": "Coulomb force problem diagram for EE-50001",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "2.692 N",
      "2.690 N",
      "2.701 N",
      "2.691 N",
      "2.696 N",
      "2.689 N"
    ],
    "correctIndex": 4,
    "explanation": "Coulomb's law gives F = k q1 q2/r^2 = 2.696 N. Governing relation: F = k |q1 q2|/r^2. Assumptions: Point charges in air, treated as vacuum. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-2501",
    "imageRole": "instructional_hint",
    "treePath": "Section 05 > Electromagnetics > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-62501",
    "topic": "Transmission Lines",
    "subtopic": "Lossless characteristic impedance",
    "prompt": "A lossless line has per-unit-length inductance L' = 250 nH/m and per-unit-length capacitance C' = 100 pF/m. What is Z0?",
    "diagram": "/question-bank/images/IMG-3126.svg",
    "diagramAlt": "Lossless characteristic impedance problem diagram for EE-62501",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "51 ohm",
      "50 ohm",
      "42 ohm",
      "57 ohm",
      "41 ohm",
      "56 ohm"
    ],
    "correctIndex": 1,
    "explanation": "For a lossless line, Z0 = sqrt(L/C) = 50 ohm. Governing relation: Z0 = sqrt(L/C). Assumptions: Lossless transmission line. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-3126",
    "imageRole": "instructional_hint",
    "treePath": "Section 06 > Transmission Lines > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-75001",
    "topic": "Power Systems",
    "subtopic": "Three-phase real power",
    "prompt": "A balanced three-phase load has line voltage 6 kV, line current 200 A, and power factor 0.85. What real power is delivered?",
    "diagram": "/question-bank/images/IMG-3751.svg",
    "diagramAlt": "Three-phase real power problem diagram for EE-75001",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "1766.1 kW",
      "1767.2 kW",
      "1766.9 kW",
      "1765.9 kW",
      "1766.7 kW",
      "1766.3 kW"
    ],
    "correctIndex": 4,
    "explanation": "Three-phase real power is P = sqrt(3)*VL*IL*pf = 1766.7 kW. Governing relation: P = sqrt(3) VL IL pf. Assumptions: Balanced three-phase load; RMS line quantities. Result is rounded to the precision shown in the choices.",
    "careerContext": "Power engineers use this when evaluating energy conversion and system behavior.",
    "imageId": "IMG-3751",
    "imageRole": "instructional_hint",
    "treePath": "Section 07 > Power Systems > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-87501",
    "topic": "Transformers and Electrical Machines",
    "subtopic": "Transformer voltage ratio",
    "prompt": "An ideal transformer has Np = 140, Ns = 80, and primary voltage 480 V. What is the secondary voltage?",
    "diagram": "/question-bank/images/IMG-4376.svg",
    "diagramAlt": "Transformer voltage ratio problem diagram for EE-87501",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "274.29 V",
      "274.21 V",
      "274.33 V",
      "274.38 V",
      "274.22 V",
      "274.20 V"
    ],
    "correctIndex": 0,
    "explanation": "For an ideal transformer, Vs/Vp = Ns/Np, so Vs = 274.29 V. Governing relation: Vs/Vp = Ns/Np. Assumptions: Ideal transformer. Result is rounded to the precision shown in the choices.",
    "careerContext": "Power engineers use this when evaluating energy conversion and system behavior.",
    "imageId": "IMG-4376",
    "imageRole": "instructional_hint",
    "treePath": "Section 08 > Transformers and Electrical Machines > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-100001",
    "topic": "Power Electronics",
    "subtopic": "Buck converter output",
    "prompt": "An ideal buck converter operating in continuous-conduction mode at steady state has Vin = 24 V and duty cycle D = 0.75. What is the output voltage?",
    "diagram": "/question-bank/images/IMG-5001.svg",
    "diagramAlt": "Buck converter output problem diagram for EE-100001",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "21 V",
      "14 V",
      "26 V",
      "18 V",
      "9 V",
      "12 V"
    ],
    "correctIndex": 3,
    "explanation": "For an ideal buck, Vo = D*Vin = 18 V. Governing relation: Vo = D Vin. Assumptions: Ideal buck converter in continuous conduction. Result is rounded to the precision shown in the choices.",
    "careerContext": "Power engineers use this when evaluating energy conversion and system behavior.",
    "imageId": "IMG-5001",
    "imageRole": "instructional_hint",
    "treePath": "Section 09 > Power Electronics > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-112501",
    "topic": "Analog Electronics and Op-Amps",
    "subtopic": "Inverting op-amp gain",
    "prompt": "An ideal inverting amplifier has Rin = 3 kohm and Rf = 9 kohm. What is the voltage gain?",
    "diagram": "/question-bank/images/IMG-5626.svg",
    "diagramAlt": "Inverting op-amp gain problem diagram for EE-112501",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "-7 V/V",
      "4 V/V",
      "-5 V/V",
      "-3 V/V",
      "-1 V/V",
      "-6 V/V"
    ],
    "correctIndex": 3,
    "explanation": "Inverting gain is Av = -Rf/Rin = -3 V/V. Governing relation: Av = -Rf/Rin. Assumptions: Ideal op-amp with negative feedback. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-5626",
    "imageRole": "instructional_hint",
    "treePath": "Section 10 > Analog Electronics and Op-Amps > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-125001",
    "topic": "Semiconductor Devices",
    "subtopic": "BJT collector current",
    "prompt": "A BJT has beta = 90 and base current 20 uA in active region. What is collector current?",
    "diagram": "/question-bank/images/IMG-6251.svg",
    "diagramAlt": "BJT collector current problem diagram for EE-125001",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "1.1 mA",
      "0.9 mA",
      "2.6 mA",
      "1.3 mA",
      "1.8 mA",
      "2.3 mA"
    ],
    "correctIndex": 4,
    "explanation": "In active region, Ic = beta*Ib = 1.8 mA. Governing relation: IC = beta IB. Assumptions: BJT is in forward-active region. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-6251",
    "imageRole": "instructional_hint",
    "treePath": "Section 11 > Semiconductor Devices > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-137501",
    "topic": "Digital Logic",
    "subtopic": "Binary state count",
    "prompt": "How many unique states can 6 binary bits represent?",
    "diagram": "/question-bank/images/IMG-6876.svg",
    "diagramAlt": "Binary state count problem diagram for EE-137501",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "62 states",
      "56 states",
      "67 states",
      "64 states",
      "60 states",
      "63 states"
    ],
    "correctIndex": 3,
    "explanation": "n bits represent 2^n states, so 2^6 = 64. Governing relation: states = 2^n. Assumptions: Independent binary bits. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-6876",
    "imageRole": "instructional_hint",
    "treePath": "Section 12 > Digital Logic > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-150001",
    "topic": "Signals and Systems",
    "subtopic": "Nyquist sampling",
    "prompt": "A signal is band-limited to 2 kHz. What is the theoretical Nyquist rate? Practical sampling must be higher.",
    "diagram": "/question-bank/images/IMG-7501.svg",
    "diagramAlt": "Nyquist sampling problem diagram for EE-150001",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "5 kHz",
      "7 kHz",
      "10 kHz",
      "13 kHz",
      "17 kHz",
      "4 kHz"
    ],
    "correctIndex": 5,
    "explanation": "Nyquist sampling requires fs >= 2*fmax = 4 kHz. Governing relation: Nyquist rate = 2 fmax. Assumptions: Ideal baseband signal supported on |f| <= fmax; practical sampling must exceed the theoretical rate. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-7501",
    "imageRole": "instructional_hint",
    "treePath": "Section 13 > Signals and Systems > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-162501",
    "topic": "Control Systems",
    "subtopic": "Unity-feedback closed-loop gain",
    "prompt": "A stable negative-unity-feedback system has scalar DC forward gain K = 3. What is the closed-loop DC gain?",
    "diagram": "/question-bank/images/IMG-8126.svg",
    "diagramAlt": "Unity-feedback closed-loop gain problem diagram for EE-162501",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "0.77",
      "0.75",
      "0.79",
      "0.70",
      "0.67",
      "0.74"
    ],
    "correctIndex": 1,
    "explanation": "Closed-loop gain is K/(1+K) = 0.75. Governing relation: T(0) = K/(1 + K). Assumptions: Negative unity feedback; scalar DC forward gain. Result is rounded to the precision shown in the choices.",
    "careerContext": "Controls engineers use this when predicting system response and stability.",
    "imageId": "IMG-8126",
    "imageRole": "instructional_hint",
    "treePath": "Section 14 > Control Systems > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-175001",
    "topic": "Communications",
    "subtopic": "AM bandwidth",
    "prompt": "A conventional AM signal has highest modulating frequency 2 kHz. What transmission bandwidth is required?",
    "diagram": "/question-bank/images/IMG-8751.svg",
    "diagramAlt": "AM bandwidth problem diagram for EE-175001",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "4 kHz",
      "19 kHz",
      "14 kHz",
      "16 kHz",
      "10 kHz",
      "9 kHz"
    ],
    "correctIndex": 0,
    "explanation": "Conventional AM bandwidth is 2*fm = 4 kHz. Governing relation: BWAM = 2 fm,max. Assumptions: Conventional double-sideband AM. Result is rounded to the precision shown in the choices.",
    "careerContext": "Communications and RF engineers use this when reasoning about signals and links.",
    "imageId": "IMG-8751",
    "imageRole": "instructional_hint",
    "treePath": "Section 15 > Communications > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-187501",
    "topic": "Measurement and Instrumentation",
    "subtopic": "ADC LSB size",
    "prompt": "A 12-bit ADC uses a 10 V reference. What is one LSB? Use the ideal unipolar convention LSB = Vref/2^N.",
    "diagram": "/question-bank/images/IMG-9376.svg",
    "diagramAlt": "ADC LSB size problem diagram for EE-187501",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "2.4414 mV",
      "2.4417 mV",
      "2.4423 mV",
      "2.4416 mV",
      "2.4418 mV",
      "2.4419 mV"
    ],
    "correctIndex": 0,
    "explanation": "Ideal LSB size is Vref/2^N = 2.4414 mV. Governing relation: LSB = Vref/2^N. Assumptions: Ideal unipolar ADC using the stated quantization-step convention. Result is rounded to the precision shown in the choices.",
    "careerContext": "Test engineers use this when interpreting measurements and instrument limits.",
    "imageId": "IMG-9376",
    "imageRole": "instructional_hint",
    "treePath": "Section 16 > Measurement and Instrumentation > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-200001",
    "topic": "PCB Design and Signal Integrity",
    "subtopic": "Trace propagation delay",
    "prompt": "A PCB trace is 4 inch long with delay 170 ps/in. What is the one-way propagation delay?",
    "diagram": "/question-bank/images/IMG-10001.svg",
    "diagramAlt": "Trace propagation delay problem diagram for EE-200001",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "673 ps",
      "680 ps",
      "688 ps",
      "689 ps",
      "684 ps",
      "681 ps"
    ],
    "correctIndex": 1,
    "explanation": "Delay equals length times delay per inch = 680 ps. Governing relation: tpd = length x delay_per_length. Assumptions: Uniform trace. Result is rounded to the precision shown in the choices.",
    "careerContext": "PCB and signal integrity engineers use this when checking board-level behavior.",
    "imageId": "IMG-10001",
    "imageRole": "instructional_hint",
    "treePath": "Section 17 > PCB Design and Signal Integrity > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-212501",
    "topic": "Embedded Systems",
    "subtopic": "UART bit time",
    "prompt": "What is the bit time for a UART baud rate of 115200 baud?",
    "diagram": "/question-bank/images/IMG-10626.svg",
    "diagramAlt": "UART bit time problem diagram for EE-212501",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "8.683 us",
      "8.679 us",
      "8.681 us",
      "8.678 us",
      "8.674 us",
      "8.686 us"
    ],
    "correctIndex": 2,
    "explanation": "Bit time is 1/baud = 8.681 us. Governing relation: tbit = 1/baud. Assumptions: One symbol per UART bit. Result is rounded to the precision shown in the choices.",
    "careerContext": "Embedded engineers use this when sizing firmware-facing hardware interfaces.",
    "imageId": "IMG-10626",
    "imageRole": "instructional_hint",
    "treePath": "Section 18 > Embedded Systems > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-225001",
    "topic": "RF and Antennas",
    "subtopic": "Free-space wavelength",
    "prompt": "Using c = 300 Mm/s, what is the approximate free-space wavelength at 200 MHz?",
    "diagram": "/question-bank/images/IMG-11251.svg",
    "diagramAlt": "Free-space wavelength problem diagram for EE-225001",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "2.2 m",
      "1.4 m",
      "1.2 m",
      "0.6 m",
      "1.5 m",
      "2.1 m"
    ],
    "correctIndex": 4,
    "explanation": "Using c approx 300 Mm/s, lambda(m) = 300/f(MHz) = 1.5 m. Governing relation: lambda = c/f. Assumptions: Free space with c approximated as 300 Mm/s. Result is rounded to the precision shown in the choices.",
    "careerContext": "Communications and RF engineers use this when reasoning about signals and links.",
    "imageId": "IMG-11251",
    "imageRole": "instructional_hint",
    "treePath": "Section 19 > RF and Antennas > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  },
  {
    "id": "EE-237501",
    "topic": "Electrical Safety and Protection",
    "subtopic": "CT secondary current",
    "prompt": "A 400:5 ideal current transformer, with saturation and ratio error neglected, carries 50 A primary current. What secondary current flows ideally?",
    "diagram": "/question-bank/images/IMG-11876.svg",
    "diagramAlt": "CT secondary current problem diagram for EE-237501",
    "difficulty": 1,
    "difficultyLabel": "Easy",
    "xp": 12,
    "options": [
      "0.620 A",
      "0.629 A",
      "0.625 A",
      "0.626 A",
      "0.627 A",
      "0.634 A"
    ],
    "correctIndex": 2,
    "explanation": "Ideal CT secondary current is Ip*(rated secondary/rated primary) = 0.625 A. Governing relation: Is = Ip x Is,rated/Ip,rated. Assumptions: Ideal current-transformer ratio; saturation and ratio error neglected. Result is rounded to the precision shown in the choices.",
    "careerContext": "Engineers use this concept when turning theory into practical design checks.",
    "imageId": "IMG-11876",
    "imageRole": "instructional_hint",
    "treePath": "Section 20 > Electrical Safety and Protection > Level 01 > Node 001",
    "verificationStatus": "Verified",
    "verificationMethod": "Verified by deterministic recomputation",
    "factCheckedAt": "2026-07-23",
    "contentVersion": "2.0",
    "difficultyCalibration": "Provisional: direct-substitution item; suitable for foundational practice.",
    "roundingPolicy": "Nearest displayed precision using decimal ROUND_HALF_UP."
  }
] as const;
